name: Monorepo CI Pipeline

on: 
    # Dispara automaaticamente ao enviar novos commits para a branch main
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    # Permite execução manual pelo painel web do github Actions
    workflow_dispatch:

# Permite cancelar as execuções anteriores na mesma branch se novos commits forem enviados
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    # Job 1 : Validações Estaticas e Teste Unitarios Rapidos (faill-fast)
    validacoes-e-testes:
        name: 1. Qualidade, Tipos e Testes Unitários
        runs-on: ubuntu-latest

        steps:
            - name: 1. Baixar o codigo-fonte
              uses: actions/checkout@v4

            - name: 2. Habilitar o pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 11
            
            - name: 3. Configurar o Node.js 24
              uses: action/setup-node@v4
              with:
                node-version: 24

            - name: 4. Instalar dependencias do backend
              run: |
                cd backend
                pnpm install --frozen-lockfile

            - name: 5. Validar Padronização de Código (ESLint)
              run: |
                cd backend
                pnpm run lint

            - name: 6. Validar Formatação de Arquivos (Prettier)
              run: |
                cd backend
                pnpm run format:check

            - name: 7. Checagem de Tipos no Backend (tsc --noEmit)
              run: |
                cd backend
                pnpm run type-check

            - name: 8. Executar Testes Unitários com Vitest
              run: |
                cd backend
                pnpm run test:run

    # Job 2: Compilação de produção e Imagens Docker (Só executa se o Job 1 passa)
    build-e-docker:
        name: 2. Compilação e imagens Docker
        needs: validacoes-e-testes
        runs-on: ubuntu-latest

        
        steps:
            - name: 1. Baixar o codigo-fonte
              uses: actions/checkout@v4

            - name: 2. Habilitar o pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 11
            
            - name: 3. Configurar o Node.js 24
              uses: action/setup-node@v4
              with:
                node-version: 24

            - name: 4. Instalar dependencias do backend
              run: |
                cd backend
                pnpm install --frozen-lockfile
    
            - name: 5. Validar tipos e Compilar o Backend (Express)
              run: |
                cd backend
                pnpm run build
              
            - name: 6. Validar Construção da imagem Docker da API
              run: |
                docker build -t api-service:test ./backend
            
            
            - name: 7. Validar Frontend (quando presente no monorepo)
              run: |
                if [ -d "app"]; then
                    echo "Subprojeto frontend encontrado. Iniciando validação..."
                    cd app
                    pnpm install --frozen-lockfile
                    pnpm run build
                    docker build -t app-service:test ./app
                else 
                    echo "Subprojeto app ainda não adicionado ao monorepo."
                fi

            - name: 8. Resumo da Execução
              run: |
                echo "### Resumo da Execução da Pipeline da CI" >> $GITHUB_STEP_SUMMARY
                echo "Integração Continua cocluida com sucesso!" >> $GITHUB_STEP_SUMMARY
                echo "- Autor: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
                echo "- Commit: ${{github.sha }}" >> $GITHUB_STEP_SUMMARY


  

   
            


            
            

